"""
scripts/create_mock_annotations.py
====================================
Creates mock PhysioNet .hea + annotation TSV files and PASCAL seg CSVs
that match the mock audio data already generated by create_mock_data.py.

Usage:
    python scripts/create_mock_annotations.py
"""

import os
import wave
import numpy as np

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PHYSIONET_BASE = os.path.join(PROJECT_ROOT, "data", "raw", "physionet2016")
PASCAL_BASE    = os.path.join(PROJECT_ROOT, "data", "raw", "pascal")


# ── Helpers ───────────────────────────────────────────────────────────────────

def wav_duration(wav_path: str) -> float:
    try:
        with wave.open(wav_path, "rb") as wf:
            return wf.getnframes() / wf.getframerate()
    except Exception:
        return 3.0


def wav_sample_rate(wav_path: str) -> int:
    try:
        with wave.open(wav_path, "rb") as wf:
            return wf.getframerate()
    except Exception:
        return 2000


def generate_cardiac_cycle_tsv(duration_sec: float, fs: int = 2000) -> list[tuple[int, int]]:
    """
    Generate synthetic cardiac-cycle state annotation rows.

    Returns a list of (end_sample, state_int) pairs simulating a realistic
    PCG annotation:
        state 1 = S1   (~100 ms)
        state 2 = systole (~250 ms)
        state 3 = S2   (~80 ms)
        state 4 = diastole (~400 ms)
    Total cycle ≈ 830 ms → ~72 BPM
    """
    # Durations in ms for each state at roughly 72 BPM
    state_durations_ms = [100, 250, 80, 400]   # S1, systole, S2, diastole
    cycle_ms = sum(state_durations_ms)           # ≈ 830 ms

    rows: list[tuple[int, int]] = []
    current_sample = 0
    total_samples = int(duration_sec * fs)

    while current_sample < total_samples:
        for state_idx, dur_ms in enumerate(state_durations_ms, start=1):
            end_sample = current_sample + int(dur_ms * fs / 1000)
            if end_sample > total_samples:
                end_sample = total_samples
            rows.append((end_sample, state_idx))
            current_sample = end_sample
            if current_sample >= total_samples:
                break

    return rows


# ── PhysioNet: .hea headers and annotation TSVs ──────────────────────────────

def create_physionet_annotations():
    """
    For every .wav in every training-X folder:
      - Write a companion .hea header file
      - Write a TSV annotation file under annotations/hand_corrected/
    """
    ann_dir = os.path.join(PHYSIONET_BASE, "annotations", "hand_corrected")
    os.makedirs(ann_dir, exist_ok=True)

    subsets = ["training-a", "training-b", "training-c", "training-e"]
    total = 0

    for subset in subsets:
        subset_dir = os.path.join(PHYSIONET_BASE, subset)
        if not os.path.isdir(subset_dir):
            continue

        for fname in sorted(os.listdir(subset_dir)):
            if not fname.endswith(".wav"):
                continue
            stem = fname[:-4]  # e.g. "a0001"
            wav_path = os.path.join(subset_dir, fname)

            fs       = wav_sample_rate(wav_path)
            duration = wav_duration(wav_path)

            # ── Write .hea file ──────────────────────────────────────────────
            hea_path = os.path.join(subset_dir, f"{stem}.hea")
            n_samples = int(duration * fs)
            with open(hea_path, "w") as f:
                # WFDB .hea first line: record_name num_signals fs num_samples
                f.write(f"{stem} 1 {fs} {n_samples}\n")
                # Signal description line (minimal)
                f.write(f"{stem}.wav 16+0 1/mV 16 0 0 0 0 PCG\n")

            # ── Write annotation TSV ─────────────────────────────────────────
            tsv_path = os.path.join(ann_dir, f"{stem}.tsv")
            rows = generate_cardiac_cycle_tsv(duration, fs)
            with open(tsv_path, "w") as f:
                for end_sample, state_int in rows:
                    f.write(f"{end_sample}\t{state_int}\n")

            total += 1

    print(f"PhysioNet: created {total} .hea + TSV annotation pairs")
    print(f"  TSVs written to: {ann_dir}")


# ── PASCAL: Atraining_normal_seg.csv and Btraining_normal_seg.csv ────────────

def generate_pascal_seg_events(duration_sec: float, fs: int) -> list[int]:
    """
    Generate alternating S1/S2 sample-index events for a PASCAL recording.
    Pattern: S1, S2, S1, S2, ...  at roughly 72 BPM
      S1 at cycle start
      S2 at ~350 ms into cycle
      Cycle = ~830 ms
    """
    s1_offset_ms = 0
    s2_offset_ms = 350
    cycle_ms     = 830

    events = []
    cycle_start_ms = 0.0
    total_ms = duration_sec * 1000

    while cycle_start_ms < total_ms:
        s1_ms = cycle_start_ms + s1_offset_ms
        s2_ms = cycle_start_ms + s2_offset_ms
        if s1_ms < total_ms:
            events.append(int(s1_ms * fs / 1000))
        if s2_ms < total_ms:
            events.append(int(s2_ms * fs / 1000))
        cycle_start_ms += cycle_ms

    return events


def create_pascal_seg_csvs():
    """
    Write Atraining_normal_seg.csv and Btraining_normal_seg.csv.

    Format (matching the real PASCAL dataset):
        filename,S1_1,S2_1,S1_2,S2_2,...
    where sample indices alternate S1/S2.
    """

    # ── Set A ────────────────────────────────────────────────────────────────
    set_a_normal_dir = os.path.join(PASCAL_BASE, "setA", "Atraining_normal")
    set_a_csv_path   = os.path.join(PASCAL_BASE, "setA", "Atraining_normal_seg.csv")

    rows_a = []
    if os.path.isdir(set_a_normal_dir):
        for fname in sorted(os.listdir(set_a_normal_dir)):
            if not fname.endswith(".wav"):
                continue
            stem     = fname[:-4]
            wav_path = os.path.join(set_a_normal_dir, fname)
            fs       = wav_sample_rate(wav_path)
            duration = wav_duration(wav_path)
            events   = generate_pascal_seg_events(duration, fs)
            rows_a.append([stem] + events)

    with open(set_a_csv_path, "w") as f:
        f.write("filename," + ",".join([f"event_{i}" for i in range(1, 20)]) + "\n")
        for row in rows_a:
            f.write(",".join(str(x) for x in row) + "\n")

    print(f"PASCAL setA: wrote {len(rows_a)} normal recordings to Atraining_normal_seg.csv")

    # ── Set B ────────────────────────────────────────────────────────────────
    set_b_normal_dir      = os.path.join(PASCAL_BASE, "setB", "Btraining_normal")
    set_b_noisynormal_dir = os.path.join(set_b_normal_dir, "Btraining_noisynormal")
    set_b_csv_path        = os.path.join(PASCAL_BASE, "setB", "Btraining_normal_seg.csv")

    rows_b = []
    for search_dir in [set_b_normal_dir, set_b_noisynormal_dir]:
        if not os.path.isdir(search_dir):
            continue
        for fname in sorted(os.listdir(search_dir)):
            if not fname.endswith(".wav"):
                continue
            stem     = fname[:-4]
            wav_path = os.path.join(search_dir, fname)
            fs       = wav_sample_rate(wav_path)
            duration = wav_duration(wav_path)
            events   = generate_pascal_seg_events(duration, fs)
            rows_b.append([stem] + events)

    with open(set_b_csv_path, "w") as f:
        f.write("filename," + ",".join([f"event_{i}" for i in range(1, 20)]) + "\n")
        for row in rows_b:
            f.write(",".join(str(x) for x in row) + "\n")

    print(f"PASCAL setB: wrote {len(rows_b)} normal recordings to Btraining_normal_seg.csv")


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("Creating mock annotation files...")
    print("=" * 60)
    create_physionet_annotations()
    create_pascal_seg_csvs()
    print("\nDone.")
